all:
  appname: bin-service
  docker_registry: nidockerhubgeneral.azurecr.io
  replicas: 2
  memory_limits: 4000Mi
  memory_requests: 4000Mi
  cpu_limits: 1
  cpu_requests: 0.4
  java_opts: -XX:MaxRAMFraction=2 -XX:+UnlockExperimentalVMOptions -Djava.security.egd=file:/dev/./urandom
  domain: ngenius-payments.com
  include_mada_scheme_bins: false
dev:
  memory_limits: 4000Mi
  memory_requests: 2631Mi
  cpu_limits: 1000m
  cpu_requests: 10m
  test_bin_info:
    - bin: 520424
      cardBrand: MASTERCARD
      issuingOrg: MASTERCARD - MEMBER TEST FACILITY
      cardType: CREDIT
      cardCategory: ACQUIRER ONLY
      issuingCountryIsoName: UNITED STATES
      issuingCountry: US
      issuingCountryIsoA3Code: USA
      issuingCountryCode: 840
      issuingOrganizationWebsite: HTTPS://WWW.MASTERCARD.US/
      issuingOrganizationPhoneNumber: 1-800-307-7309
      cardDesignation: PERSONAL
uat:
  test_bin_info:
    - bin: 520424
      cardBrand: MASTERCARD
      issuingOrg: MASTERCARD - MEMBER TEST FACILITY
      cardType: CREDIT
      cardCategory: ACQUIRER ONLY
      issuingCountryIsoName: UNITED STATES
      issuingCountry: US
      issuingCountryIsoA3Code: USA
      issuingCountryCode: 840
      issuingOrganizationWebsite: HTTPS://WWW.MASTERCARD.US/
      issuingOrganizationPhoneNumber: 1-800-307-7309
      cardDesignation: PERSONAL
oc-infradev:
  cluster_name: ksa
  domain: infradev.ksa.ngenius-payments.com
  include_mada_scheme_bins: true
  test_bin_info:
    - bin: 520424
      cardBrand: MASTERCARD
      issuingOrg: MASTERCARD - MEMBER TEST FACILITY
      cardType: CREDIT
      cardCategory: ACQUIRER ONLY
      issuingCountryIsoName: UNITED STATES
      issuingCountry: US
      issuingCountryIsoA3Code: USA
      issuingCountryCode: 840
      issuingOrganizationWebsite: HTTPS://WWW.MASTERCARD.US/
      issuingOrganizationPhoneNumber: 1-800-307-7309
      cardDesignation: PERSONAL
oc-uat:
  cluster_name: ksa
  domain: uat.ksa.ngenius-payments.com
  include_mada_scheme_bins: true
  test_bin_info:
    - bin: 520424
      cardBrand: MASTERCARD
      issuingOrg: MASTERCARD - MEMBER TEST FACILITY
      cardType: CREDIT
      cardCategory: ACQUIRER ONLY
      issuingCountryIsoName: UNITED STATES
      issuingCountry: US
      issuingCountryIsoA3Code: USA
      issuingCountryCode: 840
      issuingOrganizationWebsite: HTTPS://WWW.MASTERCARD.US/
      issuingOrganizationPhoneNumber: 1-800-307-7309
      cardDesignation: PERSONAL
oc-production:
  cluster_name: ksa
  domain: production.ksa.ngenius-payments.com
  include_mada_scheme_bins: true
