server:
  port: 8080
  forward-headers-strategy: native

logging.level.org.springframework.web: INFO

spring:
  application:
    name: @application.name@

## Spring Boot Actuator Info Endpoint Customization
info:
  # static properties
  app:
    name: ${spring.application.name}
    description: NI Micro Service
    version: @application.version@
    buildDate: @application.buildDate@

# Metrics related configurations
management:
  info:
    env:
      enabled: true
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
    health:
      show-details: always
  endpoints.web.exposure.include: info,health,prometheus
  metrics.export.prometheus.enabled: true

